"""update payment table

Revision ID: 70f503f26bf2
Revises: e0d449d22321
Create Date: 2026-07-06 00:17:54.485552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '70f503f26bf2'
down_revision: Union[str, Sequence[str], None] = 'e0d449d22321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payment_method',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('cash', 'upi', 'credit_card', 'debit_card', name='paymentmethod'),
               existing_nullable=False)
    op.alter_column('payments', 'payment_status',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('pending', 'success', 'failed', name='paymentstatus'),
               existing_nullable=False)
    op.create_unique_constraint(None, 'payments', ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.alter_column('payments', 'payment_status',
               existing_type=sa.Enum('pending', 'success', 'failed', name='paymentstatus'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.Enum('cash', 'upi', 'credit_card', 'debit_card', name='paymentmethod'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
