"""add is_deleted to products

Revision ID: b108ad3fec11
Revises: 09aef8655e4b
Create Date: 2026-06-28 18:30:38.373615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b108ad3fec11'
down_revision: Union[str, Sequence[str], None] = '09aef8655e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_deleted')
    # ### end Alembic commands ###
