"""add refunded payment status

Revision ID: f517f926271f
Revises: 70f503f26bf2
Create Date: 2026-07-08 17:01:59.107181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f517f926271f'
down_revision: Union[str, Sequence[str], None] = '70f503f26bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payments",
        "payment_status",
        existing_type=sa.Enum(
            "pending",
            "success",
            "failed",
            name="paymentstatus"
        ),
        type_=sa.Enum(
            "pending",
            "success",
            "failed",
            "refunded",
            name="paymentstatus"
        ),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payments",
        "payment_status",
        existing_type=sa.Enum(
            "pending",
            "success",
            "failed",
            "refunded",
            name="paymentstatus"
        ),
        type_=sa.Enum(
            "pending",
            "success",
            "failed",
            name="paymentstatus"
        ),
        existing_nullable=False
    )
    # ### end Alembic commands ###
